# Rust 代码格式化配置
# 确保项目代码风格统一

# 基本设置
tab_spaces = 2
hard_tabs = false
max_width = 100

# 导入设置
reorder_imports = true
reorder_modules = true
remove_nested_parens = true

# 函数设置
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# 控制流设置
control_brace_style = "AlwaysSameLine"

# 注释设置
comment_width = 80
wrap_comments = true
normalize_comments = true

# 字符串设置
format_strings = true

# 其他设置
use_small_heuristics = "Default"
merge_derives = true
use_field_init_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_layout = "Mixed"
group_imports = "StdExternalCrate"

# 尾随逗号
trailing_comma = "Vertical"
trailing_semicolon = true

# 空格设置
spaces_around_ranges = false
type_punctuation_density = "Wide"

# 换行设置
newline_style = "Unix"
format_code_in_doc_comments = true
doc_comment_code_block_width = 100