# Rust 代码格式化配置
# 设置缩进为 2 个空格

tab_spaces = 2
hard_tabs = false
max_width = 100
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_block_trailing_comma = false
use_field_init_shorthand = false
force_explicit_abi = true